export type Achievement = {
  id: string;
  period: "大一全年" | "大一上" | "大一下" | "大一暑假" | "大二上";
  date: string;
  category:
    | "竞赛获奖"
    | "竞赛经历"
    | "学术成果"
    | "学生工作"
    | "志愿服务"
    | "文体经历"
    | "项目实践"
    | "班级荣誉"
    | "成长节点";
  role: string;
  title: string;
  description: string;
  sortDate?: string;
  status?: "获奖" | "进行中" | "已完成" | "任职中" | "未获奖";
  featured?: boolean;
  result?: string;
  englishTitle?: string;
  accent?: "blue" | "copper" | "ink";
  evidenceId?: string;
};

export const periodOrder = ["大一全年", "大一上", "大一下", "大一暑假", "大二上"] as const;

export const achievements: Achievement[] = [
  {
    id: "comprehensive-english-representative",
    period: "大一全年",
    date: "2025.09—2026.06",
    sortDate: "2025-09-01",
    category: "学生工作",
    role: "英语2025-02班综合英语课代表",
    title: "综合英语课代表",
    description:
      "贯穿整个大一，负责教师、助教与同学之间的沟通，完成作业收发、课程通知、学习事务协调，并协助制定学期计划、保障课堂设备运行和整理期末复习资料。",
    status: "已完成",
    evidenceId: "evidence-comprehensive-english-representative",
  },
  {
    id: "student-union-organization",
    period: "大一全年",
    date: "2025.09—2026.06",
    sortDate: "2025-09-02",
    category: "学生工作",
    role: "外国语学院学生会组织部干事",
    title: "学生会组织部干事",
    description: "贯穿整个大一，参与学院大型活动、校级活动与现场事务执行。",
    status: "已完成",
    evidenceId: "evidence-student-union-organization",
  },
  {
    id: "youth-volunteer-projects",
    period: "大一全年",
    date: "2025.09—2026.06",
    sortDate: "2025-09-03",
    category: "志愿服务",
    role: "西南交通大学青年志愿者联合会活动项目部干事",
    title: "活动项目部干事",
    description:
      "参与文明校园志愿者监督、文明校园物资交接，以及志愿服务项目执行与材料整理。",
    status: "已完成",
    evidenceId: "evidence-activity-project-department",
  },
  {
    id: "debate-team",
    period: "大一全年",
    date: "2025—2026",
    sortDate: "2025-09-04",
    category: "文体经历",
    role: "外国语学院大学生综合素质拓展协会辩论队队员",
    title: "辩论队队员",
    description: "随学院辩论队参加新生杯辩论赛，帮助学院晋级八强。",
    status: "已完成",
    evidenceId: "evidence-debate-team",
  },
  {
    id: "volunteer-hours",
    period: "大一全年",
    date: "截至2026.06",
    sortDate: "2026-06-30",
    category: "志愿服务",
    role: "志愿服务累计记录",
    title: "50小时志愿服务记录",
    description:
      "“志愿四川”累计志愿服务50小时；第二课堂累计81学时，其中社会实践与志愿服务类26学时。",
    status: "已完成",
    evidenceId: "evidence-volunteer",
  },
  {
    id: "welcome-gala",
    period: "大一上",
    date: "2025.12.14",
    sortDate: "2025-12-14",
    category: "学生工作",
    role: "外国语学院学生会组织部干事",
    title: "学院迎新晚会组织工作",
    description: "协助组织数百人规模的外国语学院迎新晚会。",
    status: "已完成",
    evidenceId: "evidence-welcome-gala-group",
  },
  {
    id: "self-study-exam-oct",
    period: "大一上",
    date: "2025.10.25—26",
    sortDate: "2025-10-25",
    category: "志愿服务",
    role: "全国高等教育自学考试西南交通大学考点志愿者",
    title: "自学考试考点志愿服务",
    description: "参加全国高等教育自学考试西南交通大学考点志愿服务。",
    status: "已完成",
    evidenceId: "evidence-self-study-2025-site",
  },
  {
    id: "volunteer-assessment",
    period: "大一上",
    date: "2025.11.02",
    sortDate: "2025-11-02",
    category: "志愿服务",
    role: "考核评分人员",
    title: "青年志愿者协会考核评分",
    description: "参与计算机与人工智能学院青年志愿者协会相关考核活动评分工作。",
    status: "已完成",
    evidenceId: "evidence-volunteer-assessment",
  },
  {
    id: "fltrp-guocai",
    period: "大一上",
    date: "2025.10.12",
    sortDate: "2025-10-12",
    category: "竞赛经历",
    role: "参赛者",
    title: "外研社“国才杯”综合赛项",
    description: "参加校赛，未获奖、未晋级。",
    status: "未获奖",
    evidenceId: "evidence-guocai-exam",
  },
  {
    id: "yunda-run",
    period: "大一上",
    date: "2025.11.23",
    sortDate: "2025-11-23",
    category: "文体经历",
    role: "参赛者",
    title: "第五届“运达杯”体育节环校跑",
    description: "参加2025年西南交通大学第五届“运达杯”体育节环校跑。",
    status: "已完成",
    evidenceId: "evidence-yunda-run-certificate",
  },
  {
    id: "dead-poets-society-paper",
    period: "大一上",
    date: "2026.01.04",
    sortDate: "2026-01-04",
    category: "学术成果",
    role: "英文论文作者",
    title: "大一上学期期末英文研究论文",
    englishTitle:
      "The Alienation of Love: Guilt, Control, and the Shadow of Filial Piety in Dead Poets Society",
    description: "以《死亡诗社》为文本，讨论爱、控制与孝道之间的张力。",
    result: "研究主题：文学文本中的亲子关系与情感控制",
    status: "已完成",
    evidenceId: "evidence-literature-paper",
  },
  {
    id: "alma-mater-presentation",
    period: "大一上",
    date: "2026.01.21",
    sortDate: "2026-01-21",
    category: "志愿服务",
    role: "返校宣讲志愿者",
    title: "母校五班返校宣讲",
    description: "回到母校，连续走进5个班级开展宣讲，分享大学学习与成长经历，激励学弟学妹。",
    status: "已完成",
    evidenceId: "evidence-alma-mater-presentation",
  },
  {
    id: "hometown-zhouzhuang",
    period: "大一上",
    date: "2026.01.28",
    sortDate: "2026-01-28",
    category: "志愿服务",
    role: "“返家乡”志愿者",
    title: "周庄古镇宣传推广",
    description: "参加“返家乡”志愿活动，对苏州周庄古镇进行宣传推广。",
    status: "已完成",
    evidenceId: "evidence-zhouzhuang-promotion",
  },
  {
    id: "sports-meeting",
    period: "大一下",
    date: "2026.04.10",
    sortDate: "2026-04-10",
    category: "学生工作",
    role: "外国语学院学生会组织部干事",
    title: "校运动会相关工作",
    description: "在校运动会中负责物资搬运、人数统计及现场纪律维护。",
    status: "已完成",
    evidenceId: "evidence-sports-signin",
  },
  {
    id: "wuzhou-style",
    period: "大一下",
    date: "2026.04.23",
    sortDate: "2026-04-23",
    category: "学生工作",
    role: "外国语学院学生会组织部干事",
    title: "“五洲风情”活动",
    description: "参与“五洲风情”活动的现场布置与摊位执勤。",
    status: "已完成",
    evidenceId: "evidence-wuzhou-duty",
  },
  {
    id: "self-study-exam-apr",
    period: "大一下",
    date: "2026.04.11—12",
    sortDate: "2026-04-11",
    category: "志愿服务",
    role: "全国高等教育自学考试西南交通大学考点志愿者",
    title: "自学考试考点志愿服务",
    description: "第二次参加全国高等教育自学考试西南交通大学考点志愿服务。",
    status: "已完成",
    evidenceId: "evidence-self-study-2026-materials",
  },
  {
    id: "childrens-day",
    period: "大一下",
    date: "2026.05.31",
    sortDate: "2026-05-31",
    category: "志愿服务",
    role: "活动志愿者",
    title: "“缤纷六一，守护童心”关爱活动",
    description: "参加社区儿童节关爱活动。",
    status: "已完成",
    evidenceId: "evidence-childrens-day-scene",
  },
  {
    id: "anniversary-uniforms",
    period: "大一下",
    date: "2026.05.09",
    sortDate: "2026-05-09",
    category: "志愿服务",
    role: "校庆志愿服务人员",
    title: "西南交通大学130周年校庆志愿服务",
    description: "协助完成校庆志愿者服装发放工作。",
    status: "已完成",
    evidenceId: "evidence-anniversary",
  },
  {
    id: "transport-public-welfare",
    period: "大一下",
    date: "2026.04.18",
    sortDate: "2026-04-18",
    category: "志愿服务",
    role: "项目材料整理人员",
    title: "“交通·公益”志愿服务季",
    description: "参与整理志愿服务季立项申报材料。",
    status: "已完成",
    evidenceId: "evidence-transport-approval",
  },
  {
    id: "gongga-cup",
    period: "大一下",
    date: "2026.04.22",
    sortDate: "2026-04-22",
    category: "文体经历",
    role: "赛事志愿者",
    title: "四川省第六季“贡嘎杯”高校男子排球专业组",
    description: "参加高校男子排球专业组赛事志愿服务工作。",
    status: "已完成",
    evidenceId: "evidence-gongga-cup-registration",
  },
  {
    id: "moot-court",
    period: "大一下",
    date: "2026.06.06",
    sortDate: "2026-06-06",
    category: "竞赛获奖",
    role: "模拟法庭赛队员",
    title: "“求索杯”模拟法庭",
    description: "参加西南交通大学公共管理学院“求索杯”校级科创竞赛模拟法庭赛。",
    status: "获奖",
    result: "校级优胜奖 · 28支队伍第7名",
    featured: true,
    accent: "blue",
    evidenceId: "evidence-moot-court",
  },
  {
    id: "neccs",
    period: "大一下",
    date: "2026.04.12",
    sortDate: "2026-04-12",
    category: "竞赛经历",
    role: "参赛者",
    title: "全国大学生英语竞赛",
    description: "参加全国大学生英语竞赛，未获奖、未晋级。",
    status: "未获奖",
    evidenceId: "evidence-neccs-exam",
  },
  {
    id: "window-stone",
    period: "大一下",
    date: "2026.07.04",
    sortDate: "2026-07-04",
    category: "竞赛获奖",
    role: "英语演讲比赛参赛者",
    title: "窗与石",
    englishTitle: "The Window and the Stone",
    description: "从苏州园林花窗与云冈石窟出发，讨论文明交流如何改变观看与创造的方式。",
    status: "获奖",
    result: "英语系实习活动演讲比赛二等奖 · 84.33分",
    featured: true,
    accent: "copper",
    evidenceId: "evidence-speech",
  },
  {
    id: "qionglai-livestream",
    period: "大一下",
    date: "2026.07.06",
    sortDate: "2026-07-06",
    category: "项目实践",
    role: "跨境电商直播实训成员",
    title: "非遗邛崃酒跨境英文直播",
    description:
      "参加英语专业认知实习中的跨境电商直播实训，承担英文台词补位、衔接救场与补充说明工作。",
    status: "获奖",
    result: "团体竞赛二等奖",
    featured: true,
    accent: "ink",
    evidenceId: "evidence-livestream",
  },
  {
    id: "ai-learning-gap-paper",
    period: "大一下",
    date: "2026.06.28",
    sortDate: "2026-06-28",
    category: "学术成果",
    role: "英文论文作者",
    title: "大一下学期期末英文研究论文",
    englishTitle:
      "Does AI Equalize Learners or Widen the Gap? Learner Agency and Skill Development in Generative AI-Assisted Learning",
    description:
      "完成约2990词、11页的英文论文，通过文献综述、机制分析与反证讨论研究学习者能动性、技能发展和教育公平。",
    status: "已完成",
    result: "研究主题：生成式AI、学习者能动性与教育公平",
    featured: true,
    accent: "blue",
    evidenceId: "evidence-ai-paper",
  },
  {
    id: "semantic-association-writing-assessment",
    period: "大一暑假",
    date: "2026.07—",
    sortDate: "2026-07-11",
    category: "学术成果",
    role: "研究与专利方案负责人",
    title: "基于语义关联分析的英语作文智能评估方法",
    description:
      "探索将语义关联分析用于英语作文的连贯性与表达质量评估，形成可用于智能评估的技术方法。",
    status: "进行中",
    result: "申请材料准备中",
  },
  {
    id: "ai-education-digital-ethics",
    period: "大一暑假",
    date: "2026.07—",
    sortDate: "2026-07-12",
    category: "学术成果",
    role: "研究者",
    title: "AI教育与数字伦理调研与研究",
    description:
      "围绕生成式AI进入教育场景后的学习公平、主体性、数据责任与数字伦理问题开展调研和研究。",
    status: "进行中",
  },
  {
    id: "ai-legal-translation",
    period: "大一暑假",
    date: "2026.07—",
    sortDate: "2026-07-13",
    category: "学术成果",
    role: "研究者",
    title: "AI与法律翻译",
    englishTitle:
      "Accuracy and Risk in Large Language Model Translation of Contracts, Regulations and Patent Texts",
    description:
      "研究大模型翻译合同、法规与专利文本时的准确性、术语一致性、责任边界与法律风险。",
    status: "进行中",
  },
  {
    id: "information-literacy",
    period: "大一下",
    date: "2026.07.05",
    sortDate: "2026-07-05",
    category: "竞赛经历",
    role: "信息素养大赛参赛成员",
    title: "我们不是在争吵，而是在被算法推着争吵",
    description: "围绕信息茧房、算法推荐与检索意识完成竞赛微视频作品。",
    status: "进行中",
    result: "信息素养大赛参赛作品 · 结果待公布",
    evidenceId: "evidence-information-literacy-script",
  },
  {
    id: "class-meeting-award",
    period: "大一下",
    date: "2026.05.19",
    sortDate: "2026-05-19",
    category: "班级荣誉",
    role: "班级成员",
    title: "《压力拜拜，快乐常在》心理主题班会",
    description: "所在班级参加2026年度西南交通大学“交心”心理班会展示会。",
    status: "获奖",
    result: "二等奖",
    evidenceId: "evidence-class-meeting",
  },
  {
    id: "league-member",
    period: "大一下",
    date: "2026.06.04",
    sortDate: "2026-06-04",
    category: "成长节点",
    role: "共青团员",
    title: "加入中国共产主义青年团",
    description: "于2026年6月4日正式加入中国共产主义青年团。",
    status: "已完成",
  },
  {
    id: "campus-bus-volunteer",
    period: "大一下",
    date: "2026.06.08、15",
    sortDate: "2026-06-08",
    category: "志愿服务",
    role: "校园校车多语种暖心志愿者",
    title: "“畅行校车，语暖中外”志愿活动",
    description: "两次参加校园校车多语种暖心志愿活动，帮助留学生顺利乘坐校车出行。",
    status: "已完成",
    evidenceId: "evidence-campus-bus-1",
  },
  {
    id: "course-development-minister",
    period: "大二上",
    date: "2026.09—",
    sortDate: "2026-09-01",
    category: "学生工作",
    role: "西南交通大学青年志愿者联合会课程建设部部长（拟于2026年9月履任）",
    title: "课程建设与宣讲运营",
    description:
      "拟于2026年9月履任，届时将参与课程素材建设、劳育课程宣讲支持、宣讲人员统筹、课程运营台账、数据整理与反馈优化。",
  },
];

export const featuredAchievements = [
  ...achievements.filter((item) => item.featured && item.id === "ai-learning-gap-paper"),
  ...achievements.filter((item) => item.featured && item.id !== "ai-learning-gap-paper"),
];

export const academicProfile = {
  semesters: [
    {
      term: "大一上",
      gpa: "3.6 / 4.0",
      rank: "专业排名 28 / 56",
      note: "已公布",
    },
    {
      term: "大一下",
      gpa: "3.8 / 4.0",
      rank: "专业排名待公布",
      note: "成绩已确认",
    },
  ],
  qualifications: [
    { label: "CET-4", value: "568", status: "已取得" },
    { label: "CET-6", value: "—", status: "成绩待公布" },
    { label: "TEM-4", value: "—", status: "未考" },
    { label: "TEM-8", value: "—", status: "未考" },
  ],
  research: [
    "2篇期末英文研究论文已完成",
    "英语作文智能评估方法：申请材料准备中",
    "AI教育与数字伦理调研与研究",
    "AI与法律翻译准确性与风险研究",
  ],
};

export const pathway = [
  {
    stage: "LANGUAGE",
    time: "持续推进",
    title: "语言与研究能力",
    description:
      "将英语专业的阅读、写作、演讲与翻译能力沉淀为稳定、可验证的学术与沟通基础，并以研究型写作持续训练问题意识。",
    focus: "研究写作 · 演讲 · 翻译",
    actions: ["夯实学术英语能力", "保持研究型写作输出", "形成基于证据的清晰表达"],
  },
  {
    stage: "RULES",
    time: "持续推进",
    title: "规则、文本与跨语境问题",
    description:
      "通过民法系统阅读、案例摘要、模拟法庭与法律英语，不把对法律的关注停留在兴趣层面，而是练习理解规则、处理文本与识别风险。",
    focus: "案例摘要 · 法律英语 · 模拟法庭",
    actions: ["形成民法与案例分析基础", "练习清晰的规则型论证", "在法律相关实践中检验问题意识"],
  },
  {
    stage: "TECH / AI",
    time: "持续推进",
    title: "技术理解与数字伦理",
    description:
      "研究智能系统如何重塑学习与法律文本，重点关注技术进入真实决策时的准确性、学习者主体性、责任边界与潜在风险。",
    focus: "AI 素养 · 数字伦理 · Legal Tech",
    actions: ["推进 AI 教育与法律翻译研究", "把技术问题与语言、规则相互连接", "以可验证文本与证据约束技术判断"],
  },
];
